# Generated by Django 5.1.15 on 2026-05-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_userprofile_equipment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hometown",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
