# Generated by Django 5.1.15 on 2026-05-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_userprofile_hometown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
