# Generated by Django 5.1.15 on 2026-05-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_ingredient_optional_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="push_token",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
