# Generated by Django 5.1.15 on 2026-05-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_recipecategory_recipe_ingredients_used_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
